import { z } from 'zod';

export const KnownProblemCodeSchema = z.enum([
  'validation_failed',
  'http_error',
  'internal_error',
  'not_found',
  'forbidden',
  'invalid_state',
  'auth_rate_limited',
  'challenge_attempts_exhausted',
  'challenge_rate_limited',
  'invalid_credentials',
  'invalid_grant',
  'invalid_return_to',
  'invalid_workload_token',
  'workload_not_trusted',
  'local_auth_disabled',
  'oidc_disabled',
  'password_auth_disabled',
  'social_provider_disabled',
  'social_provider_required',
  'not_authenticated',
  'device_not_authenticated',
  'worker_not_authenticated',
  'application_slug_exists',
  'workspace_slug_exists',
  'release_version_exists',
  'artifact_name_exists',
  'artifact_not_declared',
  'artifact_signer_mismatch',
  'manifest_identity_mismatch',
  'manifest_integrity_mismatch',
  'manifest_signature_mismatch',
  'release_id_mismatch',
  'channel_changed',
  'validation_queue_unavailable',
  'object_not_uploaded',
  'object_size_mismatch',
  'object_checksum_mismatch',
  'object_content_type_mismatch',
  'object_metadata_mismatch',
  'authorization_lease_signing_unavailable',
  'device_credential_exists',
  'device_key_scope_changed',
  'installation_artifact_unavailable',
  'installation_not_actionable',
  'installation_release_invalid',
  'installation_revision_ahead',
  'permission_approval_required',
  'permission_requirement_changed',
  'run_attempt_changed',
  'run_report_mismatch',
  'schedule_changed',
  'schedule_revision_ahead',
]);
export type KnownProblemCode = z.infer<typeof KnownProblemCodeSchema>;

/** Stable validation semantics; `message` is intentionally not part of this wire shape. */
export const ProblemValidationIssueSchema = z.object({
  path: z.array(z.union([z.string(), z.number().int()])),
  code: z.string().min(1).max(80),
  params: z.record(z.string(), z.unknown()).optional(),
});
export type ProblemValidationIssue = z.infer<typeof ProblemValidationIssueSchema>;

export const ProblemDetailsSchema = z.object({
  type: z.string().url(),
  title: z.string(),
  status: z.number().int().min(400).max(599),
  detail: z.string().optional(),
  instance: z.string().optional(),
  code: z.string().regex(/^[a-z][a-z0-9_]*$/),
  errors: z.unknown().optional(),
});
export type ProblemDetails = z.infer<typeof ProblemDetailsSchema>;
